"""
Django settings for portfolio_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)sgd(u75t=ksyd9(u4l@115c51xxcu0-x$a*s%n^j8f^743k$d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Unfold Admin apps
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "unfold.contrib.simple_history",

    # Django core apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'django_quill',
    'import_export',
    'simple_history',
    'widget_tweaks',
    'modeltranslation',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_filters',
    
    # Local apps
    'portfolio',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    "django.middleware.locale.LocaleMiddleware",
]

ROOT_URLCONF = 'portfolio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'portfolio.context_processors.site_settings',
                'portfolio.context_processors.navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Internationalization
LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True
 

# Supported languages
LANGUAGES = [
    ('en', _('English')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    ('de', _('German')),
    ('hi', _('Hindi')),
    ('ne', _('Nepali')),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

# Static files
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

from django.utils.translation import get_language_info

# Unfold Admin Configuration
UNFOLD = {

    

    "SITE_TITLE": "Nishan Portfolio Admin",
    "SITE_HEADER": "Portfolio Dashboard",
    "SITE_DESCRIPTION": "Welcome to the Portfolio Admin Dashboard. Manage your portfolio content, including projects, blogs, and testimonials, all in one place.",

    "SITE_URL": "/",
    "SHOW_LANGUAGES": True,
    
    "SITE_LOGO": {
        "light": lambda request: "/static/img/nkclogo.png",
        "dark": lambda request: "/static/img/nkclogo.png",
       
    },
        "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/png",
            "href": lambda request: "/static/img/favicon-32x32.png",
        },
    ],
    
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            # {
            #     "title": _("Dashboard"),
            #     "items": [
            #         {
            #             "title": _("Analytics"),
            #             "icon": "dashboard",
            #             "link": "/admin/dashboard/",
            #         },
            #     ],
            # },
            {
                "title": _("Portfolio"),
                "items": [
                    {
                        "title": _("About"),
                        "icon": "person",
                        "link": "/admin/portfolio/about/",
                    },
                    {
                        "title": _("Services"),
                        "icon": "business_center",
                        "link": "/admin/portfolio/service/",
                    },
                    {
                        "title": _("Projects"),
                        "icon": "folder",
                        "link": "/admin/portfolio/project/",
                    },
                    {
                        "title": _("Blogs"),
                        "icon": "article",
                        "link": "/admin/portfolio/blog/",
                    },
                    {
                        "title": _("Gallery"),
                        "icon": "photo_library",
                        "link": "/admin/portfolio/gallery/",
                    },
                    {
                        "title": _("Testimonials"),
                        "icon": "format_quote",
                        "link": "/admin/portfolio/testimonial/",
                    },
                    {
                        "title": _("Certificates"),
                        "icon": "badge",
                        "link": "/admin/portfolio/certificate/",
                    },
                    {
                        "title": _("Skills"),
                        "icon": "psychology",
                        "link": "/admin/portfolio/skill/",
                    },
                ],
            },
            {
                "title": _("Contact & FAQ"),
                "items": [
                    {
                        "title": _("Contact Messages"),
                        "icon": "contact_mail",
                        "link": "/admin/portfolio/contactmessage/",
                    },
                    {
                        "title": _("FAQ"),
                        "icon": "help",
                        "link": "/admin/portfolio/faq/",
                    },
                ],
            },
        ],
    },
    "TABS": [
        {
            "models": [
                "portfolio.about",
                "portfolio.skill",
            ],
            "items": [
                {
                    "title": _("Profile Information"),
                    "icon": "person",
                    "link": "/admin/portfolio/about/",
                },
                {
                    "title": _("Skills"),
                    "icon": "psychology",
                    "link": "/admin/portfolio/skill/",
                },
            ],
        },
    ],
}