# Generated by Django 6.0 on 2025-12-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Certificate Image'),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Certificate Image'),
        ),
    ]
